<?php
/**
 * Plugin Name: FormsWP (Analog)
 * Plugin URI: https://github.com/Fess007/FormsWP
 * Description: Lightweight forms plugin scaffold (analogue). Adds admin styles and enqueues assets. Generated by assistant.
 * Version: 0.1.0
 * Author: Generated
 * Text Domain: formswp
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Define plugin constants.
if ( ! defined( 'FORMSWP_VERSION' ) ) {
    define( 'FORMSWP_VERSION', '0.1.0' );
}

if ( ! defined( 'FORMSWP_PLUGIN_FILE' ) ) {
    define( 'FORMSWP_PLUGIN_FILE', __FILE__ );
}

if ( ! defined( 'FORMSWP_PLUGIN_DIR' ) ) {
    define( 'FORMSWP_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
}

if ( ! defined( 'FORMSWP_PLUGIN_URL' ) ) {
    define( 'FORMSWP_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
}

// Enqueue admin styles.
function formswp_admin_assets( $hook ) {
    // Load only on our plugin pages - for now load everywhere in admin for demo.
    wp_enqueue_style( 'formswp-admin-form-templates', FORMSWP_PLUGIN_URL . 'assets/css/admin-form-templates.css', [], FORMSWP_VERSION );
    wp_enqueue_style( 'formswp-form-embed-wizard', FORMSWP_PLUGIN_URL . 'assets/css/form-embed-wizard.css', [], FORMSWP_VERSION );
}
add_action( 'admin_enqueue_scripts', 'formswp_admin_assets' );

// Simple activation hook.
function formswp_activate() {
    // Placeholder for activation tasks (create tables, options).
}
register_activation_hook( FORMSWP_PLUGIN_FILE, 'formswp_activate' );

// Simple deactivation hook.
function formswp_deactivate() {
    // Placeholder for deactivation tasks.
}
register_deactivation_hook( FORMSWP_PLUGIN_FILE, 'formswp_deactivate' );

// Add a top-level admin menu for demonstration.
function formswp_admin_menu() {
    add_menu_page( 'FormsWP', 'FormsWP', 'manage_options', 'formswp', 'formswp_admin_page', 'dashicons-feedback', 6 );
}
add_action( 'admin_menu', 'formswp_admin_menu' );

function formswp_admin_page() {
    ?>
    <div class="wrap wpforms-admin-page">
        <h1>FormsWP (Demo)</h1>
        <p>This is a lightweight scaffold created by the assistant. Add forms, assets and logic as needed.</p>
    </div>
    <?php
}

?>